### ISSUE TITLE
reduce the useState

### ISSUE THREAD

**Issue by JeganMurugan01** [Nigalraj/api_react_task#2]
const [show, setShow] = useState(false);
  const [data, setData] = useState([]);
  const [modalData, setModalData] = useState(false);

  const [selectedRow, setSelectedRow] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [currentPage, setCurrentPage] = useState(number[0]);
  check these @Nigalraj

**Comment by Nigalraj** [comment]
fixed successfully
